# Generated by Django 4.2.5 on 2023-09-12 19:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_company_project_company"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "Companies"},
        ),
    ]
