# Generated by Django 4.2.5 on 2023-09-05 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="assigned",
            new_name="assignee",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="started_date",
            new_name="start_date",
        ),
    ]
