# Generated by Django 4.2.5 on 2023-09-12 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="active",
        ),
        migrations.RemoveField(
            model_name="note",
            name="email",
        ),
    ]
