# Generated by Django 4.2.5 on 2023-09-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_remove_note_active_remove_note_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
