# Generated by Django 4.2.5 on 2023-09-15 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0007_alter_note_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed"]},
        ),
    ]
